### ISSUE TITLE
[Bug]: Invalid option name: 'hidden'

### ISSUE THREAD

**Issue by Aasim-A** [chrisgrieser/nvim-early-retirement#1]
### Bug Description

Hey, thanks for making this useful plugin!
The latest commit had caused the following error:
```
Error executing vim.schedule lua callback: ...nvim/lazy/nvim-early-retirement/lua/early-retirement.lua:20: Invalid option name: 'hidden'
```

### neovim version

```Text
NVIM v0.9.0-dev-1326+g7c8c15507
```

### Make sure you have done the following

- [x] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
oops, yeah made a dumb mistake. Thanks, is fixed
