### ISSUE TITLE
Feature Request: only close buffers with zero diagnostics

### ISSUE THREAD

**Issue by snoblenet** [chrisgrieser/nvim-early-retirement#11]
### Feature Requested

I'm writing a function for myself that automatically creates a hidden buffer for every path listed when you call `npx tsc --noEmit` in the shell.

This is so the diagnostics for each such file are added to my QuickList.

Would it be possible to add an option to `nvim-early-retirement` to only close dormant hidden buffers when they have zero diagnostic messages attached?

(Or a configuration option where the user can enter an arbitrary `function CloseIf(bufnr)... end` function of their own choice.)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Wouldn't `ignoreSpecialBuftypes` cover this if you gave those buffers a buftype? Or `ignoreFilenamePattern` if you gave those buffers a particular name?

**Comment by chrisgrieser** [comment]
I came up with a simple solution: Setting `vim.b.ignore_early_retirement = true` in a buffer makes the plugin completely ignore that buffer. That way, users have full flexibility to determine when to not auto-close buffers.
