### ISSUE TITLE
Feature Request: Option to keep buffers from inactive tabs

### ISSUE THREAD

**Issue by akhilman** [chrisgrieser/nvim-early-retirement#4]
### Feature Requested

I use tabs to organize my workflow. With early retirement enabled I suddenly discovered that all my tabs were closed except active one.
It would be nice to have an option to keep buffers from inactive tabs from being closed.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I don't really that work with tabs at all, so I am not very familiar with them. Is there a method to tell whether a buffer is open in an inactive tab? If there is such a method, it's be easy to add.

**Comment by akhilman** [comment]
I have some working code in my luapad. I'll do PR in few days.

**Comment by akhilman** [comment]
My bad. Seems like I forgot to update plugin and had a version before 71522986cddc016c93491420c2abe06124affc5b.
The current `main` does not destroy any tabs.

**Comment by chrisgrieser** [comment]
😅 

Nevertheless, thanks for the effort! Feel free to make another PR, when you have a different idea for this plugin
