### ISSUE TITLE
Feature Request: Don't close buffers when neovim is restarted

### ISSUE THREAD

**Issue by mmirus** [chrisgrieser/nvim-early-retirement#7]
### Feature Requested

Currently, if you load a few buffers and then quit and restart neovim, all but the current and alternate buffers will be gone when neovim starts back up, regardless of how long any of the buffers were unused for.

Would it be possible to close buffers solely based on how long they have been idle, and not clear them out on restart?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Keeping buffers across restarts is feels a bit too far off from goal of this plugin. 

There are Session Manager plugins that do that though

**Comment by mmirus** [comment]
@chrisgrieser sorry, that was pretty unclear of me. I already have a session manager plugin that keeps the buffers across restarts, but this plugin stops that from happening (either by interfering in some way or by closing the buffers, which I am assuming is what's happening).

In other words, without this plugin, the buffers stick around when I restart. With this plugin, they're gone as I described, only keeping the current and alternate buffer.

Perhaps this should have been a bug ticket rather than a feature request, but I wasn't sure if this was intended behavior or not.

**Comment by chrisgrieser** [comment]
Oh I see - just today I actually added a new setting for that, checkout the readme and #6.

**Comment by mmirus** [comment]
If I understand that option correctly, currently I'd have to choose between:

- never have this plugin retire unloaded buffers, regardless of how long they've been unused, but persisting them between restarts works
- let the plugin retire them based on how long they've been unused, but lose them on restart (even if they were just opened right before the restart)

If that's correct, I think a better version of the second option would be:

- let the plugin retire them when they have been unused for too long, but don't lose them on restart

Since the concept of this plugin (as I understand it) is to tidy up the buffer list based on how long it's been since a buffer was used, also clearing it out on restart (despite the normal behavior of the season management plugin) seems unexpected.

**Comment by chrisgrieser** [comment]
Hmm, the tricky thing is, that since I do not use session managers myself, I am not very confident to get it right since I am not really familiar with the workflow people like you have. To avoid unnecessarily cumbersome back-and-forth, it's probably easiest if someone who uses a session manager make a PR implementing these things?

nvim-early-retirement is a really simple plugin (less than 60 lines total), so I making PRs to it shouldn't be hard. Maybe @nmrtv also has any good ideas here in this regard?

**Comment by nmrtv** [comment]
Well, I think that we can change the logic, how we handle `lastused` time and wait for at least `retirementAgeMins` after startup. Maybe by just changing buffer `lastused` time if that is possible. I'll look at this later.

**Comment by nmrtv** [comment]
Another simple possibility is to start timer after `retirementAgeMins`.

```lua
	timer:start(retirementAgeMins * 60000, 10000, vim.schedule_wrap(checkOutdatedBuffer)) -- schedule wrapper required for timers
```
Not checked this, but probably it should work.

**Comment by chrisgrieser** [comment]
@mmirus I merged a PR from @nmrtv that should fix that issue

**Comment by mmirus** [comment]
> @mmirus I merged a PR from @nmrtv that should fix that issue

Thanks both! I should be able to check it out tomorrow.

**Comment by mmirus** [comment]
This seems to be working as expected now. Thank you both!
