### ISSUE TITLE
Feature Request: If in a git repo, check if file has changes

### ISSUE THREAD

**Issue by npx** [chrisgrieser/nvim-early-retirement#9]
### Feature Requested

I like the idea of this plug in! But in my workflow I think the relevant files are the ones that I actually edited (even when saved). In this case the git status would be quite helpful. What do you think?

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Actually, there is already a different plugin for that :)
https://github.com/axkirillov/hbac.nvim

(closing, since it would be duplicate work to implement that here as well)
